# Online Config Subscribe
# Clash For Magisk
# Credits [fyn170](https://github.com/fyn170/conf-cfm)
----
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
external-ui: "/dashboard/dist"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
dns:
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - https://dns.adguard.com/dns-query
  - https://dns-google.com/dns-query
  - tls://dns.adguard.com
  - tls://dns-google.com/
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
proxies:
proxy-providers:
  Server:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/akun/akun.yaml"
    path: "./confs/akun/akun.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
proxy-groups:
- name: 18+
  type: select
  proxies:
  - REJECT
  - Server
- name: ADS
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: Server
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Server
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
- RULE-SET,18+,Server
- RULE-SET,Ads,ADS
- RULE-SET,Direct,DIRECT
- RULE-SET,Gaming,Server
- RULE-SET,Reject,REJECT
- RULE-SET,Sosmed,Server
- RULE-SET,Stream,Server
- MATCH,GLOBAL
rule-providers:
  18+:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/saru.yaml"
    path: "./confs/rule/saru.yaml"
  Ads:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/ads.yaml"
    path: "./confs/rule/ads.yaml"
  Direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/direct.yaml"
    path: "./confs/rule/direct.yaml"
  Gaming:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/gaming.yaml"
    path: "./confs/rule/gaming.yaml"
  Reject:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/reject.yaml"
    path: "./confs/rule/reject.yaml"
  Sosmed:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml"
    path: "./confs/rule/sosmed.yaml"
  Stream:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml"
    path: "./confs/rule/stream.yaml"
